export enum GasKeys {
  ADDRESS_ACCESS = 'ADDRESS_ACCESS',
  STORAGE_READ = 'STORAGE_READ',
  STORAGE_WRITE = 'STORAGE_WRITE',
  MEMORY = 'MEMORY',
  CALL = 'CALL',
  SUB_CONTEXT = 'SUB_CONTEXT',
  BASE_GAS = 'BASE_GAS',
}
